[install]
exact = true
saveTextLockfile = true
auto = "disable"
linker = "isolated"
minimumReleaseAge = 259200
ignoreScripts = true
frozenLockfile = true
logLevel = "warn"

[install.lockfile]
save = true