// ─── < Imports > ────────────────────────────────────────────────────

use std::fs;
use std::path::{Path, PathBuf};

use crate::agent::{AgentRegistration, load_agent_registry};
use crate::config::ConfigError;

// ─── < Structs > ────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShimInstallReport {
    launcher_dir: PathBuf,
    launchers: Vec<LauncherShim>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShimListReport {
    launcher_dir: PathBuf,
    launchers: Vec<LauncherShimStatus>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LauncherShim {
    agent_id: String,
    command: String,
    real_path: String,
    shim_path: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LauncherShimStatus {
    agent_id: String,
    command: String,
    real_path: String,
    shim_path: PathBuf,
    installed: bool,
}

// ─── < Public Functions > ───────────────────────────────────────────

pub fn install_agent_launchers(registry_path: &Path, launcher_dir: &Path) -> Result<ShimInstallReport, ConfigError> {
    let registry = load_agent_registry(registry_path)?;

    fs::create_dir_all(launcher_dir).map_err(|source| ConfigError::CreateDir {
        path: launcher_dir.display().to_string(),
        source,
    })?;

    let mut launchers = Vec::new();

    for agent in registry.agents().iter().filter(|agent| agent.enabled()) {
        let shim_path = launcher_dir.join(agent.command());
        let content = launcher_script(agent);

        fs::write(&shim_path, content).map_err(|source| ConfigError::Write {
            path: shim_path.display().to_string(),
            source,
        })?;

        make_executable(&shim_path)?;

        launchers.push(LauncherShim {
            agent_id: agent.id().to_string(),
            command: agent.command().to_string(),
            real_path: agent.path().to_string(),
            shim_path,
        });
    }

    launchers.sort_by(|left, right| left.command.cmp(&right.command));

    Ok(ShimInstallReport {
        launcher_dir: launcher_dir.to_path_buf(),
        launchers,
    })
}

pub fn list_agent_launchers(registry_path: &Path, launcher_dir: &Path) -> Result<ShimListReport, ConfigError> {
    let registry = load_agent_registry(registry_path)?;

    let mut launchers = registry
        .agents()
        .iter()
        .filter(|agent| agent.enabled())
        .map(|agent| {
            let shim_path = launcher_dir.join(agent.command());

            LauncherShimStatus {
                agent_id: agent.id().to_string(),
                command: agent.command().to_string(),
                real_path: agent.path().to_string(),
                installed: shim_path.is_file(),
                shim_path,
            }
        })
        .collect::<Vec<_>>();

    launchers.sort_by(|left, right| left.command.cmp(&right.command));

    Ok(ShimListReport {
        launcher_dir: launcher_dir.to_path_buf(),
        launchers,
    })
}

// ─── < Implementations > ────────────────────────────────────────────

impl ShimInstallReport {
    pub fn launcher_dir(&self) -> &Path {
        &self.launcher_dir
    }

    pub fn launchers(&self) -> &[LauncherShim] {
        &self.launchers
    }
}

impl ShimListReport {
    pub fn launcher_dir(&self) -> &Path {
        &self.launcher_dir
    }

    pub fn launchers(&self) -> &[LauncherShimStatus] {
        &self.launchers
    }
}

impl LauncherShim {
    pub fn agent_id(&self) -> &str {
        &self.agent_id
    }

    pub fn command(&self) -> &str {
        &self.command
    }

    pub fn real_path(&self) -> &str {
        &self.real_path
    }

    pub fn shim_path(&self) -> &Path {
        &self.shim_path
    }
}

impl LauncherShimStatus {
    pub fn agent_id(&self) -> &str {
        &self.agent_id
    }

    pub fn command(&self) -> &str {
        &self.command
    }

    pub fn real_path(&self) -> &str {
        &self.real_path
    }

    pub fn shim_path(&self) -> &Path {
        &self.shim_path
    }

    pub fn installed(&self) -> bool {
        self.installed
    }
}

// ─── < Private Functions > ──────────────────────────────────────────

fn launcher_script(agent: &AgentRegistration) -> String {
    let agent_id = shell_single_quote(agent.id());
    let command = shell_single_quote(agent.command());
    let real_path = shell_single_quote(agent.path());

    format!(
        r#"#!/usr/bin/env sh
# Generated by ARC. Do not edit by hand.

ARC_AGENT_ID={agent_id}
ARC_AGENT_COMMAND={command}
ARC_AGENT_REAL_PATH={real_path}

export ARC_SOURCE="$ARC_AGENT_ID"
export ARC_AGENT_COMMAND
export ARC_AGENT_REAL_PATH

if [ ! -x "$ARC_AGENT_REAL_PATH" ]; then
  echo "ARC launcher error: real agent binary not found or not executable: $ARC_AGENT_REAL_PATH" >&2
  exit 127
fi

exec "$ARC_AGENT_REAL_PATH" "$@"
"#
    )
}

fn shell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(unix)]
fn make_executable(path: &Path) -> Result<(), ConfigError> {
    use std::os::unix::fs::PermissionsExt;

    let mut permissions = fs::metadata(path)
        .map_err(|source| ConfigError::Read {
            path: path.display().to_string(),
            source,
        })?
        .permissions();

    permissions.set_mode(0o755);

    fs::set_permissions(path, permissions).map_err(|source| ConfigError::Write {
        path: path.display().to_string(),
        source,
    })
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> Result<(), ConfigError> {
    Ok(())
}
